### PR TITLE
Adding translation support

### PR DESCRIPTION
**Pull request by rluders**
This PR adds translation support to the game. It is pretty easy and very straightforward, I'm not doing anything fancy here. The translations are stored inside a `.csv` file (utf-8) and loaded using the Godot Locale support.

This PR will add also the Brazilian Portuguese translation to the game, so... yeah, later other translations can be added by other contributors.

### CODE REVIEW

**Comment by cybtachyon** [comment]
Excited to see this land, thanks!

**Comment by rluders** [comment]
@RoddieKieley @ernesgonzalez33 what do you think?

**Comment by ergonzal22** [comment]
@rluders great idea! I will test it when I have the time and maybe add Spanish too!! You can merge it if you see it works. Or we can wait for @RoddieKieley's approval

**Comment by rluders** [comment]
@ernesgonzalez33 actually I was testing it right now, and I think that I found a bug related to the `OptionButton`. But, yeah, go for it... Add the Spanish too! :+1:

**Comment by rluders** [comment]
Now it is working as it should be. 100% sure. I'll merge it.

**Pull request merged**
