### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Raygun4K**
Art files for character.

### CODE REVIEW

**Comment by rluders** [comment]
Well, we need to find a better place to store the art sources. I'm not saying that can't be inside this repository, but, we probably need to put the files inside some folder, otherwise it will become chaos.

My suggestion is to move the `.ai` files to the `Assets` folder, and create a folder named `editable` and put all the editable files inside this folder (if necessary also create subfolders inside this structure as well).

**Review by rluders — CHANGES_REQUESTED** [review]
Well, we need to find a better place to store the art sources. I'm not saying that can't be inside this repository, but, we probably need to put the files inside some folder, otherwise it will become chaos.

My suggestion is to move the .ai files to the Assets folder, and create a folder named editable and put all the editable files inside this folder (if necessary also create subfolders inside this structure as well).

**Review by RoddieKieley — COMMENTED** [review]
I think that this repository should largely map 1 to 1 with the files required to do a build of the game, potentially taking multiple platforms into account in the longer term. If not the repo size will get bloated, take longer to download, diff, update, etc. 

As such raw assets that are not directly in use by the game should likely be elsewhere. Will follow up in chat to discuss.

**Comment by RoddieKieley** [comment]
@Raygun4K @rluders Apologies for taking so long to get to this!

**Pull request closed without merging**
